### PR TITLE
update plugin vim-airline github url

### PR DESCRIPTION
**Pull request by ycz0926**

### CODE REVIEW

**Comment by ycz0926** [comment]
en ... when i start up the yavide gui, it reports a error that tells me i should replace the orignal url with the new one.

**Comment by JBakamovic** [comment]
I think it applies for themes url only. You should test the fix before you send a pull request. I don't think this is right.

**Comment by ycz0926** [comment]
i got it, thanks.

**Comment by JBakamovic** [comment]
This pull request is now addressed and fixed with commit `7f7de3a`.

**Pull request closed without merging**
